apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
        - name: db-service
          image: gcr.io/threadit-api/db-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 300m
              memory: 2Gi
          env:
            - name: SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: DB_SERVICE_PORT
            - name: MONGO_URI
              value: "mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongodb:27017/$(MONGO_INITDB_DATABASE)?authSource=admin"
          envFrom:
            - secretRef:
                name: mongo-secret
            - configMapRef:
                name: threadit-config
          volumeMounts:
            - mountPath: /var/secret/gcp/
              name: bucket-credentials
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 60
            timeoutSeconds: 4
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 30
            timeoutSeconds: 4
          startupProbe:
            tcpSocket:
              port: 50051
            periodSeconds: 2
            failureThreshold: 90
      volumes:
        - name: bucket-credentials
          secret:
            secretName: bucket-secret
            items:
              - key: gcs-key.json
                path: gcs-key.json
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: db-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: db-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80