openapi: 3.1.0
info:
  title: VoteService API
  description: API for managing votes in threads and comments in the Threadit application.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: http://localhost:8000
    description: Local server
tags:
  - name: Votes
    description: Operations related to votes
paths:
  /votes/thread/{thread_id}/upvote:
    post:
      operationId: upvoteThread
      tags:
        - vote-service
      summary: Upvote Thread
      parameters:
        - $ref: "#/components/parameters/thread_id"
      responses:
        "200":
          description: The logged user successfully upvoted the thread.
          content:
            application/json:
              schema:
                type: "null"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          description: Authentication is required to access the requested resource. The
            client must include the appropriate credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
      security:
        - bearerAuth: []
  /votes/thread/{thread_id}/downvote:
    post:
      operationId: downvoteThread
      tags:
        - vote-service
      summary: Downvote Thread
      parameters:
        - $ref: "#/components/parameters/thread_id"
      responses:
        "200":
          description: The logged user successfully downvoted the thread.
          content:
            application/json:
              schema:
                type: "null"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          description: Authentication is required to access the requested resource. The
            client must include the appropriate credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
      security:
        - bearerAuth: []
  /votes/comment/{comment_id}/upvote:
    post:
      operationId: upvoteComment
      tags:
        - vote-service
      summary: Upvote Comment
      parameters:
        - $ref: "#/components/parameters/comment_id"
      responses:
        "200":
          description: The logged user sucessfully upvoted the comment.
          content:
            application/json:
              schema:
                type: "null"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          description: Authentication is required to access the requested resource. The
            client must include the appropriate credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
      security:
        - bearerAuth: []
  /votes/comment/{comment_id}/downvote:
    post:
      operationId: downvoteComment
      tags:
        - vote-service
      summary: Downvote Comment
      parameters:
        - $ref: "#/components/parameters/comment_id"
      responses:
        "200":
          description: The user successfully downvoted the comment.
          content:
            application/json:
              schema:
                type: "null"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          description: Authentication is required to access the requested resource. The
            client must include the appropriate credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
      security:
        - bearerAuth: []
  /votes/comment/{comment_id}:
    delete:
      operationId: removeCommentVote
      tags:
        - vote-service
      summary: Remove Comment Vote
      parameters:
        - $ref: "#/components/parameters/comment_id"
      responses:
        "200":
          description: The logged user successfully removed the vote in the comment.
          content:
            application/json:
              schema:
                type: "null"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          description: Authentication is required to access the requested resource. The
            client must include the appropriate credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "404":
          $ref: "#/components/responses/NotFound"
      security:
        - bearerAuth: []
  /votes/thread/{thread_id}:
    delete:
      operationId: removeThreadVote
      tags:
        - vote-service
      summary: Remove Thread Vote
      parameters:
        - $ref: "#/components/parameters/thread_id"
      responses:
        "200":
          description: The logged user successfully removed the vote in the thread.
          content:
            application/json:
              schema:
                type: "null"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          description: Authentication is required to access the requested resource. The
            client must include the appropriate credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "404":
          $ref: "#/components/responses/NotFound"
      security:
        - bearerAuth: []
components:
  responses:
    Conflict:
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
      description: The request could not be completed due to a conflict with the
        current state of the resource. Resolve the conflict and try again.
    BadRequest:
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              errors:
                type: array
                items:
                  type: object
                  required:
                    - message
                  properties:
                    message:
                      type: string
              message:
                type: string
      description: The server could not understand the request due to invalid syntax.
        The client should modify the request and try again.
    Unauthorized:
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
      description: Authentication is required to access the requested resource. The
        client must include the appropriate credentials.
    NotFound:
      description: The server cannot find the requested resource. The endpoint may be
        invalid or the resource may no longer exist.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
    InternalServerErrror:
      description: The server encountered an unexpected condition that prevented it
        from fulfilling the request. Report the issue to the support team if it
        persists.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Authentication Token
      bearerFormat: JWT
  parameters:
    thread_id:
      name: thread_id
      in: path
      required: true
      schema:
        type: string
    comment_id:
      name: comment_id
      in: path
      required: true
      schema:
        type: string