openapi: 3.0.0
info:
  title: vote-service.proto
  version: version not set
tags:
  - name: VoteService
paths:
  "/votes/comment/{commentId}/down":
    post:
      operationId: VoteService_DownvoteComment
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties: {}
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rpcStatus"
      parameters:
        - name: commentId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VoteServiceDownvoteCommentBody"
        required: true
      tags:
        - VoteService
  "/votes/comment/{commentId}/up":
    post:
      operationId: VoteService_UpvoteComment
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties: {}
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rpcStatus"
      parameters:
        - name: commentId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VoteServiceUpvoteCommentBody"
        required: true
      tags:
        - VoteService
  "/votes/thread/{threadId}/down":
    post:
      operationId: VoteService_DownvoteThread
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties: {}
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rpcStatus"
      parameters:
        - name: threadId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VoteServiceDownvoteThreadBody"
        required: true
      tags:
        - VoteService
  "/votes/thread/{threadId}/up":
    post:
      operationId: VoteService_UpvoteThread
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties: {}
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rpcStatus"
      parameters:
        - name: threadId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VoteServiceUpvoteThreadBody"
        required: true
      tags:
        - VoteService
components:
  schemas:
    VoteServiceDownvoteCommentBody:
      type: object
    VoteServiceDownvoteThreadBody:
      type: object
    VoteServiceUpvoteCommentBody:
      type: object
    VoteServiceUpvoteThreadBody:
      type: object
    protobufAny:
      type: object
      properties:
        "@type":
          type: string
      additionalProperties: {}
    rpcStatus:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: "#/components/schemas/protobufAny"
