apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-service
  template:
    metadata:
      labels:
        app: vote-service
    spec:
      containers:
        - name: vote-service
          image: gcr.io/threadit-api/vote-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50055
          resources:
            requests:
              cpu: 20m
              memory: 40Mi
            limits:
              cpu: 100m
              memory: 200Mi
          env:
            - name: SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: VOTE_SERVICE_PORT
            - name: THREAD_SERVICE_HOST
              value: "thread-service"
            - name: THREAD_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: THREAD_SERVICE_PORT
            - name: COMMENT_SERVICE_HOST
              value: "comment-service"
            - name: COMMENT_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: COMMENT_SERVICE_PORT
          readinessProbe:
            tcpSocket:
              port: 50055
            initialDelaySeconds: 6
            timeoutSeconds: 4
          livenessProbe:
            tcpSocket:
              port: 50055
            initialDelaySeconds: 6
            timeoutSeconds: 4
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vote-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vote-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80