apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: threadit
data:
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HTTP_ENABLED: "true"
  KC_PROXY: "edge" 