http:
  middlewares:
    cors:
      headers:
        accessControlAllowMethods: ["GET", "POST", "PATCH", "PUT", "DELETE", "OPTIONS"]
        accessControlAllowOriginList: ["*"]
        accessControlAllowHeaders: ["Origin", "Accept", "Content-Type", "X-Requested-With", "Authorization"]
        accessControlMaxAge: 100
        addVaryHeader: true

    api-strip-prefix:
      stripPrefix:
        prefixes: ["/api"]

  routers:
    communities:
      rule: "PathPrefix(`/api/communities`)"
      service: "community-service"
      entryPoints: ["web"]
      middlewares:
        - "cors"
        - "api-strip-prefix"

    threads:
      rule: "PathPrefix(`/api/threads`)"
      service: "thread-service"
      entryPoints: ["web"]
      middlewares:
        - "cors"
        - "api-strip-prefix"

    comments:
      rule: "PathPrefix(`/api/comments`)"
      service: "comment-service"
      entryPoints: ["web"]
      middlewares:
        - "cors"
        - "api-strip-prefix"

    votes:
      rule: "PathPrefix(`/api/votes`)"
      service: "vote-service"
      entryPoints: ["web"]
      middlewares:
        - "cors"
        - "api-strip-prefix"

    search:
      rule: "PathPrefix(`/api/search`)"
      service: "search-service"
      entryPoints: ["web"]
      middlewares:
        - "cors"
        - "api-strip-prefix"

    popular:
      rule: "PathPrefix(`/api/popular`)"
      service: "popular-service"
      entryPoints: ["web"]
      middlewares:
        - "cors"
        - "api-strip-prefix"

  services: # TODO: Check if env variables can be used
    community-service:
      loadBalancer:
        servers:
          - url: "http://grpc-gateway:8080/communities"

    thread-service:
      loadBalancer:
        servers:
          - url: "http://grpc-gateway:8080/threads"

    comment-service:
      loadBalancer:
        servers:
          - url: "http://grpc-gateway:8080/comments"

    vote-service:
      loadBalancer:
        servers:
          - url: "http://grpc-gateway:8080/votes"

    search-service:
      loadBalancer:
        servers:
          - url: "http://grpc-gateway:8080/search"

    popular-service:
      loadBalancer:
        servers:
          - url: "http://grpc-gateway:8080/popular"
