// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: social-service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserRequest) Reset() {
	*x = FollowUserRequest{}
	mi := &file_social_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserRequest) ProtoMessage() {}

func (x *FollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserRequest.ProtoReflect.Descriptor instead.
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return file_social_service_proto_rawDescGZIP(), []int{0}
}

func (x *FollowUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersRequest) Reset() {
	*x = GetFollowersRequest{}
	mi := &file_social_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersRequest) ProtoMessage() {}

func (x *GetFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersRequest.ProtoReflect.Descriptor instead.
func (*GetFollowersRequest) Descriptor() ([]byte, []int) {
	return file_social_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetFollowersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFollowersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersResponse) Reset() {
	*x = GetFollowersResponse{}
	mi := &file_social_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersResponse) ProtoMessage() {}

func (x *GetFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersResponse.ProtoReflect.Descriptor instead.
func (*GetFollowersResponse) Descriptor() ([]byte, []int) {
	return file_social_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetFollowersResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingRequest) Reset() {
	*x = GetFollowingRequest{}
	mi := &file_social_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingRequest) ProtoMessage() {}

func (x *GetFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingRequest) Descriptor() ([]byte, []int) {
	return file_social_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetFollowingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingResponse) Reset() {
	*x = GetFollowingResponse{}
	mi := &file_social_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingResponse) ProtoMessage() {}

func (x *GetFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingResponse) Descriptor() ([]byte, []int) {
	return file_social_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetFollowingResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type FollowCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowCommunityRequest) Reset() {
	*x = FollowCommunityRequest{}
	mi := &file_social_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowCommunityRequest) ProtoMessage() {}

func (x *FollowCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowCommunityRequest.ProtoReflect.Descriptor instead.
func (*FollowCommunityRequest) Descriptor() ([]byte, []int) {
	return file_social_service_proto_rawDescGZIP(), []int{5}
}

func (x *FollowCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

type GetCommunityFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommunityFollowersRequest) Reset() {
	*x = GetCommunityFollowersRequest{}
	mi := &file_social_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommunityFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommunityFollowersRequest) ProtoMessage() {}

func (x *GetCommunityFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommunityFollowersRequest.ProtoReflect.Descriptor instead.
func (*GetCommunityFollowersRequest) Descriptor() ([]byte, []int) {
	return file_social_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetCommunityFollowersRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

type GetCommunityFollowersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommunityFollowersResponse) Reset() {
	*x = GetCommunityFollowersResponse{}
	mi := &file_social_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommunityFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommunityFollowersResponse) ProtoMessage() {}

func (x *GetCommunityFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommunityFollowersResponse.ProtoReflect.Descriptor instead.
func (*GetCommunityFollowersResponse) Descriptor() ([]byte, []int) {
	return file_social_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetCommunityFollowersResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_social_service_proto protoreflect.FileDescriptor

const file_social_service_proto_rawDesc = "" +
	"\n" +
	"\x14social-service.proto\x12\x04vote\x1a\x1bgoogle/protobuf/empty.proto\",\n" +
	"\x11FollowUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\".\n" +
	"\x13GetFollowersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"1\n" +
	"\x14GetFollowersResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\".\n" +
	"\x13GetFollowingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"1\n" +
	"\x14GetFollowingResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\";\n" +
	"\x16FollowCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\"A\n" +
	"\x1cGetCommunityFollowersRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\":\n" +
	"\x1dGetCommunityFollowersResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds2\x93\x04\n" +
	"\rSocialService\x12=\n" +
	"\n" +
	"FollowUser\x12\x17.vote.FollowUserRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\fUnfollowUser\x12\x17.vote.FollowUserRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\fGetFollowers\x12\x19.vote.GetFollowersRequest\x1a\x1a.vote.GetFollowersResponse\x12E\n" +
	"\fGetFollowing\x12\x19.vote.GetFollowingRequest\x1a\x1a.vote.GetFollowingResponse\x12G\n" +
	"\x0fFollowCommunity\x12\x1c.vote.FollowCommunityRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x11UnfollowCommunity\x12\x1c.vote.FollowCommunityRequest\x1a\x16.google.protobuf.Empty\x12`\n" +
	"\x15GetCommunityFollowers\x12\".vote.GetCommunityFollowersRequest\x1a#.vote.GetCommunityFollowersResponseB\x1aZ\x18social-service/src/pb;pbb\x06proto3"

var (
	file_social_service_proto_rawDescOnce sync.Once
	file_social_service_proto_rawDescData []byte
)

func file_social_service_proto_rawDescGZIP() []byte {
	file_social_service_proto_rawDescOnce.Do(func() {
		file_social_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_social_service_proto_rawDesc), len(file_social_service_proto_rawDesc)))
	})
	return file_social_service_proto_rawDescData
}

var file_social_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_social_service_proto_goTypes = []any{
	(*FollowUserRequest)(nil),             // 0: vote.FollowUserRequest
	(*GetFollowersRequest)(nil),           // 1: vote.GetFollowersRequest
	(*GetFollowersResponse)(nil),          // 2: vote.GetFollowersResponse
	(*GetFollowingRequest)(nil),           // 3: vote.GetFollowingRequest
	(*GetFollowingResponse)(nil),          // 4: vote.GetFollowingResponse
	(*FollowCommunityRequest)(nil),        // 5: vote.FollowCommunityRequest
	(*GetCommunityFollowersRequest)(nil),  // 6: vote.GetCommunityFollowersRequest
	(*GetCommunityFollowersResponse)(nil), // 7: vote.GetCommunityFollowersResponse
	(*emptypb.Empty)(nil),                 // 8: google.protobuf.Empty
}
var file_social_service_proto_depIdxs = []int32{
	0, // 0: vote.SocialService.FollowUser:input_type -> vote.FollowUserRequest
	0, // 1: vote.SocialService.UnfollowUser:input_type -> vote.FollowUserRequest
	1, // 2: vote.SocialService.GetFollowers:input_type -> vote.GetFollowersRequest
	3, // 3: vote.SocialService.GetFollowing:input_type -> vote.GetFollowingRequest
	5, // 4: vote.SocialService.FollowCommunity:input_type -> vote.FollowCommunityRequest
	5, // 5: vote.SocialService.UnfollowCommunity:input_type -> vote.FollowCommunityRequest
	6, // 6: vote.SocialService.GetCommunityFollowers:input_type -> vote.GetCommunityFollowersRequest
	8, // 7: vote.SocialService.FollowUser:output_type -> google.protobuf.Empty
	8, // 8: vote.SocialService.UnfollowUser:output_type -> google.protobuf.Empty
	2, // 9: vote.SocialService.GetFollowers:output_type -> vote.GetFollowersResponse
	4, // 10: vote.SocialService.GetFollowing:output_type -> vote.GetFollowingResponse
	8, // 11: vote.SocialService.FollowCommunity:output_type -> google.protobuf.Empty
	8, // 12: vote.SocialService.UnfollowCommunity:output_type -> google.protobuf.Empty
	7, // 13: vote.SocialService.GetCommunityFollowers:output_type -> vote.GetCommunityFollowersResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_social_service_proto_init() }
func file_social_service_proto_init() {
	if File_social_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_service_proto_rawDesc), len(file_social_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_social_service_proto_goTypes,
		DependencyIndexes: file_social_service_proto_depIdxs,
		MessageInfos:      file_social_service_proto_msgTypes,
	}.Build()
	File_social_service_proto = out.File
	file_social_service_proto_goTypes = nil
	file_social_service_proto_depIdxs = nil
}
