apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-gateway
  template:
    metadata:
      labels:
        app: grpc-gateway
    spec:
      containers:
      - name: grpc-gateway
        image: gcr.io/threadit-api/grpc-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 40m
            memory: 80Mi
          limits:
            cpu: 120m
            memory: 240Mi
        env:
        - name: GRPC_GATEWAY_PORT
          valueFrom:
            configMapKeyRef:
              name: threadit-config
              key: GRPC_GATEWAY_PORT
        - name: COMMUNITY_SERVICE_HOST
          value: "community-service"
        - name: COMMUNITY_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: threadit-config
              key: COMMUNITY_SERVICE_PORT
        - name: THREAD_SERVICE_HOST
          value: "thread-service"
        - name: THREAD_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: threadit-config
              key: THREAD_SERVICE_PORT
        - name: COMMENT_SERVICE_HOST
          value: "comment-service"
        - name: COMMENT_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: threadit-config
              key: COMMENT_SERVICE_PORT
        - name: VOTE_SERVICE_HOST
          value: "vote-service"
        - name: VOTE_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: threadit-config
              key: VOTE_SERVICE_PORT
        - name: SEARCH_SERVICE_HOST
          value: "search-service"
        - name: SEARCH_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: threadit-config
              key: SEARCH_SERVICE_PORT
        - name: POPULAR_SERVICE_HOST
          value: "popular-service"
        - name: POPULAR_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: threadit-config
              key: POPULAR_SERVICE_PORT
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-gateway-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc-gateway
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80