apiVersion: apps/v1
kind: Deployment
metadata:
  name: popular-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: popular-service
  template:
    metadata:
      labels:
        app: popular-service
    spec:
      containers:
        - name: popular-service
          image: gcr.io/threadit-api/popular-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50057
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "384Mi"
          env:
            - name: SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: POPULAR_SERVICE_PORT
            - name: THREAD_SERVICE_HOST
              value: "thread-service"
            - name: THREAD_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: THREAD_SERVICE_PORT
            - name: COMMENT_SERVICE_HOST
              value: "comment-service"
            - name: COMMENT_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: COMMENT_SERVICE_PORT
          readinessProbe:
            tcpSocket:
              port: 50057
            initialDelaySeconds: 6
            timeoutSeconds: 4
          livenessProbe:
            tcpSocket:
              port: 50057
            initialDelaySeconds: 6
            timeoutSeconds: 4
