openapi: 3.1.0
info:
  title: FeedService API
  description: API for retrieving personalized user feeds in the Threadit application.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: http://localhost:8000
    description: Local server
tags:
  - name: Feeds
    description: Operations related to user feeds
paths:  
  /feeds:
    get:
      summary: Get the user's personalized feed
      operationId: getUserFeed
      tags:
        - Feeds
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 1
        - name: page_size
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 10
        - name: sort
          in: query
          description: Sorting options
          required: false
          schema:
            type: string
            enum: [new, trending, top]
            default: new
      responses:
        "200":
          description: List of feeds
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Feed"
                  pagination:
                    $ref: "#/components/schemas/Pagination"
        "401":
          description: Unauthorized access
components:
  schemas:
    Feed:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum: [post, comment]
          description: Whether the item is a post or comment
        communityId:
          type: string
          format: uuid
        title:
          type: string
          nullable: true
        content:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Pagination:
      type: object
      properties:
        current_page:
          type: integer
        per_page:
          type: integer
        total_items:
          type: integer
        total_pages:
          type: integer
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT