apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community-service
  template:
    metadata:
      labels:
        app: community-service
    spec:
      containers:
      - name: community-service
        image: gcr.io/fcul2025/community-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50052
        env:
        - name: SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: threadit-config
              key: COMMUNITY_SERVICE_PORT
        - name: DB_SERVICE_HOST
          value: "db-service"
        - name: DB_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: threadit-config
              key: DB_SERVICE_PORT
        - name: THREAD_SERVICE_HOST
          value: "thread-service"
        - name: THREAD_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: threadit-config
              key: THREAD_SERVICE_PORT
