apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataset-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: dataset-disk
    fsType: ext4
