# traefik/values.yaml

replicaCount: 1

resources:
  requests:
    cpu: 20m
    memory: 40Mi
  limits:
    cpu: 100m
    memory: 100Mi

# TODO: If needed, uncomment and configure HPA settings
#autoscaling:
#  enabled: true
#  maxReplicas: 2
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 60