# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/VALUES.md

# autoscaling: # TODO: If needed, uncomment and configure HPA settings
#   enabled: true
#   maxReplicas: 2
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 60
