# traefik/values.yaml

replicaCount: 1

resources:
  requests:
    cpu: 40m
    memory: 80Mi
  limits:
    cpu: 120m
    memory: 240Mi

# TODO: If needed, uncomment and configure HPA settings
#autoscaling:
#  enabled: true
#  maxReplicas: 2
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 60