apiVersion: apps/v1
kind: Deployment
metadata:
  name: thread-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thread-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: thread-service
    spec:
      containers:
        - name: thread-service
          image: gcr.io/threadit-api/thread-service:latest
          ports:
            - containerPort: 50053
          env:
            - name: SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: THREAD_SERVICE_PORT
            - name: DB_SERVICE_HOST
              value: "db-service"
            - name: DB_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: DB_SERVICE_PORT
            - name: COMMUNITY_SERVICE_HOST
              value: "community-service"
            - name: COMMUNITY_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: COMMUNITY_SERVICE_PORT