apiVersion: apps/v1
kind: Deployment
metadata:
  name: thread-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thread-service
  template:
    metadata:
      labels:
        app: thread-service
    spec:
      containers:
        - name: thread-service
          image: gcr.io/threadit-api/thread-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50053
          resources:
            requests:
              cpu: 20m
              memory: 40Mi
            limits:
              cpu: 100m
              memory: 200Mi
          env:
            - name: SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: THREAD_SERVICE_PORT
            - name: DB_SERVICE_HOST
              value: "db-service"
            - name: DB_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: DB_SERVICE_PORT
            - name: COMMUNITY_SERVICE_HOST
              value: "community-service"
            - name: COMMUNITY_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: COMMUNITY_SERVICE_PORT
          readinessProbe:
            tcpSocket:
              port: 50053
            initialDelaySeconds: 6
            timeoutSeconds: 4
          livenessProbe:
            tcpSocket:
              port: 50053
            initialDelaySeconds: 6
            timeoutSeconds: 4
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: thread-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: thread-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60