apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community-service
  template:
    metadata:
      labels:
        app: community-service
    spec:
      containers:
        - name: community-service
          image: gcr.io/threadit-api/community-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50052
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 50m
              memory: 100Mi
          env:
            - name: SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: COMMUNITY_SERVICE_PORT
            - name: DB_SERVICE_HOST
              value: "db-service"
            - name: DB_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: DB_SERVICE_PORT
            - name: THREAD_SERVICE_HOST
              value: "thread-service"
            - name: THREAD_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: THREAD_SERVICE_PORT
          readinessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 6
            timeoutSeconds: 4
          livenessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 6
            timeoutSeconds: 4
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: community-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: community-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60