apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: community-service
    spec:
      containers:
        - name: community-service
          image: gcr.io/threadit-api/community-service:latest
          ports:
            - containerPort: 50052
          env:
            - name: SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: COMMUNITY_SERVICE_PORT
            - name: DB_SERVICE_HOST
              value: "db-service"
            - name: DB_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: DB_SERVICE_PORT
            - name: THREAD_SERVICE_HOST
              value: "thread-service"
            - name: THREAD_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: threadit-config
                  key: THREAD_SERVICE_PORT
