// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: community-service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Community struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IconUrl       string                 `protobuf:"bytes,5,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Community) Reset() {
	*x = Community{}
	mi := &file_community_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Community) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Community) ProtoMessage() {}

func (x *Community) ProtoReflect() protoreflect.Message {
	mi := &file_community_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Community.ProtoReflect.Descriptor instead.
func (*Community) Descriptor() ([]byte, []int) {
	return file_community_service_proto_rawDescGZIP(), []int{0}
}

func (x *Community) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Community) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Community) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Community) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Community) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *Community) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Community) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	TotalItems    int32                  `protobuf:"varint,3,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_community_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_community_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_community_service_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *Pagination) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *Pagination) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type ListCommunitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	SortBy        string                 `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommunitiesRequest) Reset() {
	*x = ListCommunitiesRequest{}
	mi := &file_community_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommunitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommunitiesRequest) ProtoMessage() {}

func (x *ListCommunitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommunitiesRequest.ProtoReflect.Descriptor instead.
func (*ListCommunitiesRequest) Descriptor() ([]byte, []int) {
	return file_community_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListCommunitiesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCommunitiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCommunitiesRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ListCommunitiesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListCommunitiesRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListCommunitiesRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type ListCommunitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Communities   []*Community           `protobuf:"bytes,1,rep,name=communities,proto3" json:"communities,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommunitiesResponse) Reset() {
	*x = ListCommunitiesResponse{}
	mi := &file_community_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommunitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommunitiesResponse) ProtoMessage() {}

func (x *ListCommunitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommunitiesResponse.ProtoReflect.Descriptor instead.
func (*ListCommunitiesResponse) Descriptor() ([]byte, []int) {
	return file_community_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListCommunitiesResponse) GetCommunities() []*Community {
	if x != nil {
		return x.Communities
	}
	return nil
}

func (x *ListCommunitiesResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CreateCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommunityRequest) Reset() {
	*x = CreateCommunityRequest{}
	mi := &file_community_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommunityRequest) ProtoMessage() {}

func (x *CreateCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommunityRequest.ProtoReflect.Descriptor instead.
func (*CreateCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCommunityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCommunityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommunityRequest) Reset() {
	*x = GetCommunityRequest{}
	mi := &file_community_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommunityRequest) ProtoMessage() {}

func (x *GetCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommunityRequest.ProtoReflect.Descriptor instead.
func (*GetCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetCommunityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommunityRequest) Reset() {
	*x = UpdateCommunityRequest{}
	mi := &file_community_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommunityRequest) ProtoMessage() {}

func (x *UpdateCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommunityRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCommunityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCommunityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCommunityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommunityRequest) Reset() {
	*x = DeleteCommunityRequest{}
	mi := &file_community_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommunityRequest) ProtoMessage() {}

func (x *DeleteCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommunityRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCommunityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UploadCommunityIconRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Icon          []byte                 `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadCommunityIconRequest) Reset() {
	*x = UploadCommunityIconRequest{}
	mi := &file_community_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadCommunityIconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCommunityIconRequest) ProtoMessage() {}

func (x *UploadCommunityIconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCommunityIconRequest.ProtoReflect.Descriptor instead.
func (*UploadCommunityIconRequest) Descriptor() ([]byte, []int) {
	return file_community_service_proto_rawDescGZIP(), []int{8}
}

func (x *UploadCommunityIconRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadCommunityIconRequest) GetIcon() []byte {
	if x != nil {
		return x.Icon
	}
	return nil
}

func (x *UploadCommunityIconRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type JoinCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCommunityRequest) Reset() {
	*x = JoinCommunityRequest{}
	mi := &file_community_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCommunityRequest) ProtoMessage() {}

func (x *JoinCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCommunityRequest.ProtoReflect.Descriptor instead.
func (*JoinCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_service_proto_rawDescGZIP(), []int{9}
}

func (x *JoinCommunityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LeaveCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveCommunityRequest) Reset() {
	*x = LeaveCommunityRequest{}
	mi := &file_community_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveCommunityRequest) ProtoMessage() {}

func (x *LeaveCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveCommunityRequest.ProtoReflect.Descriptor instead.
func (*LeaveCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_service_proto_rawDescGZIP(), []int{10}
}

func (x *LeaveCommunityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCommunityMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommunityMembersRequest) Reset() {
	*x = ListCommunityMembersRequest{}
	mi := &file_community_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommunityMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommunityMembersRequest) ProtoMessage() {}

func (x *ListCommunityMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommunityMembersRequest.ProtoReflect.Descriptor instead.
func (*ListCommunityMembersRequest) Descriptor() ([]byte, []int) {
	return file_community_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListCommunityMembersRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListCommunityMembersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCommunityMembersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCommunityMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberIds     []string               `protobuf:"bytes,1,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommunityMembersResponse) Reset() {
	*x = ListCommunityMembersResponse{}
	mi := &file_community_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommunityMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommunityMembersResponse) ProtoMessage() {}

func (x *ListCommunityMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommunityMembersResponse.ProtoReflect.Descriptor instead.
func (*ListCommunityMembersResponse) Descriptor() ([]byte, []int) {
	return file_community_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListCommunityMembersResponse) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *ListCommunityMembersResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_community_service_proto protoreflect.FileDescriptor

const file_community_service_proto_rawDesc = "" +
	"\n" +
	"\x17community-service.proto\x12\tcommunity\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\x01\n" +
	"\tCommunity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x19\n" +
	"\bicon_url\x18\x05 \x01(\tR\aiconUrl\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8c\x01\n" +
	"\n" +
	"Pagination\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x1f\n" +
	"\vtotal_items\x18\x03 \x01(\x05R\n" +
	"totalItems\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\xb4\x01\n" +
	"\x16ListCommunitiesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12\x17\n" +
	"\asort_by\x18\x05 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\tR\tsortOrder\"\x88\x01\n" +
	"\x17ListCommunitiesResponse\x126\n" +
	"\vcommunities\x18\x01 \x03(\v2\x14.community.CommunityR\vcommunities\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.community.PaginationR\n" +
	"pagination\"N\n" +
	"\x16CreateCommunityRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"%\n" +
	"\x13GetCommunityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x16UpdateCommunityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"(\n" +
	"\x16DeleteCommunityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"]\n" +
	"\x1aUploadCommunityIconRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04icon\x18\x02 \x01(\fR\x04icon\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\"&\n" +
	"\x14JoinCommunityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15LeaveCommunityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x1bListCommunityMembersRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"t\n" +
	"\x1cListCommunityMembersResponse\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x01 \x03(\tR\tmemberIds\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.community.PaginationR\n" +
	"pagination2\xeb\x05\n" +
	"\x10CommunityService\x12X\n" +
	"\x0fListCommunities\x12!.community.ListCommunitiesRequest\x1a\".community.ListCommunitiesResponse\x12J\n" +
	"\x0fCreateCommunity\x12!.community.CreateCommunityRequest\x1a\x14.community.Community\x12D\n" +
	"\fGetCommunity\x12\x1e.community.GetCommunityRequest\x1a\x14.community.Community\x12J\n" +
	"\x0fUpdateCommunity\x12!.community.UpdateCommunityRequest\x1a\x14.community.Community\x12L\n" +
	"\x0fDeleteCommunity\x12!.community.DeleteCommunityRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x13UploadCommunityIcon\x12%.community.UploadCommunityIconRequest\x1a\x14.community.Community\x12H\n" +
	"\rJoinCommunity\x12\x1f.community.JoinCommunityRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x0eLeaveCommunity\x12 .community.LeaveCommunityRequest\x1a\x16.google.protobuf.Empty\x12g\n" +
	"\x14ListCommunityMembers\x12&.community.ListCommunityMembersRequest\x1a'.community.ListCommunityMembersResponseB\x1dZ\x1bcommunity-service/src/pb;pbb\x06proto3"

var (
	file_community_service_proto_rawDescOnce sync.Once
	file_community_service_proto_rawDescData []byte
)

func file_community_service_proto_rawDescGZIP() []byte {
	file_community_service_proto_rawDescOnce.Do(func() {
		file_community_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_community_service_proto_rawDesc), len(file_community_service_proto_rawDesc)))
	})
	return file_community_service_proto_rawDescData
}

var file_community_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_community_service_proto_goTypes = []any{
	(*Community)(nil),                    // 0: community.Community
	(*Pagination)(nil),                   // 1: community.Pagination
	(*ListCommunitiesRequest)(nil),       // 2: community.ListCommunitiesRequest
	(*ListCommunitiesResponse)(nil),      // 3: community.ListCommunitiesResponse
	(*CreateCommunityRequest)(nil),       // 4: community.CreateCommunityRequest
	(*GetCommunityRequest)(nil),          // 5: community.GetCommunityRequest
	(*UpdateCommunityRequest)(nil),       // 6: community.UpdateCommunityRequest
	(*DeleteCommunityRequest)(nil),       // 7: community.DeleteCommunityRequest
	(*UploadCommunityIconRequest)(nil),   // 8: community.UploadCommunityIconRequest
	(*JoinCommunityRequest)(nil),         // 9: community.JoinCommunityRequest
	(*LeaveCommunityRequest)(nil),        // 10: community.LeaveCommunityRequest
	(*ListCommunityMembersRequest)(nil),  // 11: community.ListCommunityMembersRequest
	(*ListCommunityMembersResponse)(nil), // 12: community.ListCommunityMembersResponse
	(*timestamppb.Timestamp)(nil),        // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 14: google.protobuf.Empty
}
var file_community_service_proto_depIdxs = []int32{
	13, // 0: community.Community.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: community.Community.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: community.ListCommunitiesResponse.communities:type_name -> community.Community
	1,  // 3: community.ListCommunitiesResponse.pagination:type_name -> community.Pagination
	1,  // 4: community.ListCommunityMembersResponse.pagination:type_name -> community.Pagination
	2,  // 5: community.CommunityService.ListCommunities:input_type -> community.ListCommunitiesRequest
	4,  // 6: community.CommunityService.CreateCommunity:input_type -> community.CreateCommunityRequest
	5,  // 7: community.CommunityService.GetCommunity:input_type -> community.GetCommunityRequest
	6,  // 8: community.CommunityService.UpdateCommunity:input_type -> community.UpdateCommunityRequest
	7,  // 9: community.CommunityService.DeleteCommunity:input_type -> community.DeleteCommunityRequest
	8,  // 10: community.CommunityService.UploadCommunityIcon:input_type -> community.UploadCommunityIconRequest
	9,  // 11: community.CommunityService.JoinCommunity:input_type -> community.JoinCommunityRequest
	10, // 12: community.CommunityService.LeaveCommunity:input_type -> community.LeaveCommunityRequest
	11, // 13: community.CommunityService.ListCommunityMembers:input_type -> community.ListCommunityMembersRequest
	3,  // 14: community.CommunityService.ListCommunities:output_type -> community.ListCommunitiesResponse
	0,  // 15: community.CommunityService.CreateCommunity:output_type -> community.Community
	0,  // 16: community.CommunityService.GetCommunity:output_type -> community.Community
	0,  // 17: community.CommunityService.UpdateCommunity:output_type -> community.Community
	14, // 18: community.CommunityService.DeleteCommunity:output_type -> google.protobuf.Empty
	0,  // 19: community.CommunityService.UploadCommunityIcon:output_type -> community.Community
	14, // 20: community.CommunityService.JoinCommunity:output_type -> google.protobuf.Empty
	14, // 21: community.CommunityService.LeaveCommunity:output_type -> google.protobuf.Empty
	12, // 22: community.CommunityService.ListCommunityMembers:output_type -> community.ListCommunityMembersResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_community_service_proto_init() }
func file_community_service_proto_init() {
	if File_community_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_community_service_proto_rawDesc), len(file_community_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_community_service_proto_goTypes,
		DependencyIndexes: file_community_service_proto_depIdxs,
		MessageInfos:      file_community_service_proto_msgTypes,
	}.Build()
	File_community_service_proto = out.File
	file_community_service_proto_goTypes = nil
	file_community_service_proto_depIdxs = nil
}
