name: Build and Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run unit tests for thread-service
        working-directory: code/services/thread-service
        run: go test ./test/...

      - name: Run unit tests for vote-service
        working-directory: code/services/vote-service
        run: go test ./test/...

      - name: Run unit tests for search-service
        working-directory: code/services/search-service
        run: go test ./test/...

      - name: Run unit tests for popular-service
        working-directory: code/services/popular-service
        run: go test ./test/...

      - name: Run unit tests for community-service
        working-directory: code/services/community-service
        run: go test ./test/...

      - name: Run unit tests for comment-service
        working-directory: code/services/comment-service
        run: go test ./test/...
